test: &default

  # Credentials for REST APIs
  client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  username: merchant_api1.puntsquad.com
  password: CMC2Z584ZQVR4AE6
  signature: AAFcWxV21C7fd0v3bYYYRCpSSRl31AdlQYpHBVBlvslAEqsG5oHJ4Xo0E
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: billing@puntsquad.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
